name: Perform Code Review tasks

on:
  pull_request:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: 🤡 Checkout
    - run: npm ci --force
    - run: npm run build --if-present
    - run: npm test
